# Site settings
title: "Zhengneng Chen's Resume"
description: "A resume of Zhengneng Chen based on GitHub Pages."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Zhengneng Chen"
resume_title:                   "Computer Science New Graduate"
resume_contact_email:           "czn9689@gmail.com"
resume_contact_telephone:       "1-(518)-888-5083"
resume_contact_address:         "Brooklyn, New York"
resume_header_contact_info: "Brooklyn, New York | 1-(518)-888-5083 | czn9689@gmail.com"
resume_header_intro: "<p>A self-motivated and enthusiastic individual seeking a full-time position.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    false
resume_section_interests:       false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/zhengnengchen"
  # resume_twitter_url:           ""
  # resume_dribbble_url:          ""
  resume_facebook_url:          "https://www.facebook.com/chenzhengneng"
  resume_linkedin_url:          "https://www.linkedin.com/in/zhengnengchen"
  resume_instagram_url:         "https://www.instagram.com/zhengnengchen/"
  # resume_website_url:           ""
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
